const mockDataResult = {
    collegeName: "ABC College",
    collegeLogo: "",
    studentPhoto: "",
    courseName: "Computer Science",
    semName: "III",
    acadamicYear: "2020-2021",
    prnNo: "PRN123456",
    seatNumber: 123,
    studentName: "John Doe",
    monthAndYear: "June 2021 BACKLOG",
    sgpi: "8.5",
    result: "successful",
    totalGrade: "A+",
    totalOfTotal: 421,
    outOfTotal: 700,
    totalCredit: 20.00,
    cg: "120.5",
    cgpa: 8.0,
    finalGrade: "A",
    principalSign: "",
    directorSign: "",
    date: "2024-01-11",
    place: "City, Country",
    universityLogo: "",
    numberOfSem: 8,
    credits: [
      {
        semName: "Sem-I",
        creditEarned: "20",
        sgpi: "8.0",
      },
      {
        semName: "Sem-II",
        creditEarned: "20.00",
        sgpi: "8.5",
      },
    ],
    subjects: [
      {
        subjectCode: "CS101",
        subjectName: "Introduction to Computer Science",
        internalMax: 50,
        internalMin: 20,
        internalObt: '45 @40',
        externalMax: 100,
        externalMin: 40,
        externalObt: '75 @5',
        totalMax: 150,
        totalMin: 60,
        totalObt: '120 @70',
        grade: "A",
        gradePoint: 9.0,
        creditPoint: 4.0,
        cg: 36.0,
      },
      {
        subjectCode: "CS101",
        subjectName: "Introduction to Computer Science",
        internalMax: 50,
        internalMin: 20,
        internalObt: 45,
        externalMax: 100,
        externalMin: 40,
        externalObt: 75,
        totalMax: 150,
        totalMin: 60,
        totalObt: 120,
        grade: "A",
        gradePoint: 9.0,
        creditPoint: 4.0,
        cg: 36.0,
      },
    ],
  };
  
  export default mockDataResult;
  